# compose.yaml
services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: test-test-tanstack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test-test-tanstack
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
